common:
  exp_name: test_exp
  save_dir: output
  seed: 17
  batch_size: 32
  num_workers: 4
  max_epochs: 200

dataset:
  folder: ML-244-review-task-3
  train_csv: train.csv
  val_csv: val.csv
  test_csv: test.csv
  img_size: 512

trainer:
  target: pytorch_lightning.Trainer
  params:
    gpus: [0]

model:
  target: Unet
  params:
    encoder_name: resnet34
    classes: 7

criterions:
- target: torch.nn.CrossEntropyLoss
  weight: 0.7
  name: cross_entropy
- target: segmentation_models_pytorch.losses.DiceLoss
  params:
    mode: multiclass
  weight: 0.3
  name: dice

optimizers:
- target: Adam
  params:
    lr: 0.001

scheduler:
  - target: CosineAnnealingLR
    params:
      T_max: 50
      eta_min: 1e-6
      last_epoch: -1

metrics:
- target: segmentation_models_pytorch.utils.metrics.IoU
  params:
    threshold: 0.5
  name: iou
  use_bg: False

callbacks:
- target: pytorch_lightning.callbacks.ModelCheckpoint
  params:
    filename: best-{epoch:02d}-{val_iou:2.2f}
    monitor: val_iou
    mode: max
    save_top_k: 1
    save_last: true
- target: pytorch_lightning.callbacks.EarlyStopping
  params:
    monitor: val_loss
    patience: 10
    mode: min

loggers:
- target: pytorch_lightning.loggers.TensorBoardLogger